//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PHCData.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PHCEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PHCEntities object using the connection string found in the 'PHCEntities' section of the application configuration file.
        /// </summary>
        public PHCEntities() : base("name=PHCEntities", "PHCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PHCEntities object.
        /// </summary>
        public PHCEntities(string connectionString) : base(connectionString, "PHCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PHCEntities object.
        /// </summary>
        public PHCEntities(EntityConnection connection) : base(connection, "PHCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Badge> Badges
        {
            get
            {
                if ((_Badges == null))
                {
                    _Badges = base.CreateObjectSet<Badge>("Badges");
                }
                return _Badges;
            }
        }
        private ObjectSet<Badge> _Badges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Challenge> Challenges
        {
            get
            {
                if ((_Challenges == null))
                {
                    _Challenges = base.CreateObjectSet<Challenge>("Challenges");
                }
                return _Challenges;
            }
        }
        private ObjectSet<Challenge> _Challenges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PetEarnBadge> PetEarnBadges
        {
            get
            {
                if ((_PetEarnBadges == null))
                {
                    _PetEarnBadges = base.CreateObjectSet<PetEarnBadge>("PetEarnBadges");
                }
                return _PetEarnBadges;
            }
        }
        private ObjectSet<PetEarnBadge> _PetEarnBadges;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PetProfile> PetProfiles
        {
            get
            {
                if ((_PetProfiles == null))
                {
                    _PetProfiles = base.CreateObjectSet<PetProfile>("PetProfiles");
                }
                return _PetProfiles;
            }
        }
        private ObjectSet<PetProfile> _PetProfiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reward> Rewards
        {
            get
            {
                if ((_Rewards == null))
                {
                    _Rewards = base.CreateObjectSet<Reward>("Rewards");
                }
                return _Rewards;
            }
        }
        private ObjectSet<Reward> _Rewards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Wallpaper> Wallpapers
        {
            get
            {
                if ((_Wallpapers == null))
                {
                    _Wallpapers = base.CreateObjectSet<Wallpaper>("Wallpapers");
                }
                return _Wallpapers;
            }
        }
        private ObjectSet<Wallpaper> _Wallpapers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Badges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBadges(Badge badge)
        {
            base.AddObject("Badges", badge);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Challenges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChallenges(Challenge challenge)
        {
            base.AddObject("Challenges", challenge);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PetEarnBadges EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPetEarnBadges(PetEarnBadge petEarnBadge)
        {
            base.AddObject("PetEarnBadges", petEarnBadge);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PetProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPetProfiles(PetProfile petProfile)
        {
            base.AddObject("PetProfiles", petProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rewards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRewards(Reward reward)
        {
            base.AddObject("Rewards", reward);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Wallpapers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWallpapers(Wallpaper wallpaper)
        {
            base.AddObject("Wallpapers", wallpaper);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="Badge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Badge : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Badge object.
        /// </summary>
        /// <param name="bId">Initial value of the BId property.</param>
        public static Badge CreateBadge(global::System.Int32 bId)
        {
            Badge badge = new Badge();
            badge.BId = bId;
            return badge;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BId
        {
            get
            {
                return _BId;
            }
            set
            {
                if (_BId != value)
                {
                    OnBIdChanging(value);
                    ReportPropertyChanging("BId");
                    _BId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BId");
                    OnBIdChanged();
                }
            }
        }
        private global::System.Int32 _BId;
        partial void OnBIdChanging(global::System.Int32 value);
        partial void OnBIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Badgename
        {
            get
            {
                return _Badgename;
            }
            set
            {
                OnBadgenameChanging(value);
                ReportPropertyChanging("Badgename");
                _Badgename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Badgename");
                OnBadgenameChanged();
            }
        }
        private global::System.String _Badgename;
        partial void OnBadgenameChanging(global::System.String value);
        partial void OnBadgenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Badgelogo
        {
            get
            {
                return _Badgelogo;
            }
            set
            {
                OnBadgelogoChanging(value);
                ReportPropertyChanging("Badgelogo");
                _Badgelogo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Badgelogo");
                OnBadgelogoChanged();
            }
        }
        private global::System.String _Badgelogo;
        partial void OnBadgelogoChanging(global::System.String value);
        partial void OnBadgelogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CDescription
        {
            get
            {
                return _CDescription;
            }
            set
            {
                OnCDescriptionChanging(value);
                ReportPropertyChanging("CDescription");
                _CDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CDescription");
                OnCDescriptionChanged();
            }
        }
        private global::System.String _CDescription;
        partial void OnCDescriptionChanging(global::System.String value);
        partial void OnCDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LDescription
        {
            get
            {
                return _LDescription;
            }
            set
            {
                OnLDescriptionChanging(value);
                ReportPropertyChanging("LDescription");
                _LDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LDescription");
                OnLDescriptionChanged();
            }
        }
        private global::System.String _LDescription;
        partial void OnLDescriptionChanging(global::System.String value);
        partial void OnLDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="cID">Initial value of the CID property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        public static Category CreateCategory(global::System.Int32 cID, global::System.String categoryName)
        {
            Category category = new Category();
            category.CID = cID;
            category.CategoryName = categoryName;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CID
        {
            get
            {
                return _CID;
            }
            set
            {
                if (_CID != value)
                {
                    OnCIDChanging(value);
                    ReportPropertyChanging("CID");
                    _CID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CID");
                    OnCIDChanged();
                }
            }
        }
        private global::System.Int32 _CID;
        partial void OnCIDChanging(global::System.Int32 value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="Challenge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Challenge : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Challenge object.
        /// </summary>
        /// <param name="cHID">Initial value of the CHID property.</param>
        /// <param name="challengeCreatedDate">Initial value of the ChallengeCreatedDate property.</param>
        public static Challenge CreateChallenge(global::System.Int32 cHID, global::System.DateTime challengeCreatedDate)
        {
            Challenge challenge = new Challenge();
            challenge.CHID = cHID;
            challenge.ChallengeCreatedDate = challengeCreatedDate;
            return challenge;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CHID
        {
            get
            {
                return _CHID;
            }
            set
            {
                if (_CHID != value)
                {
                    OnCHIDChanging(value);
                    ReportPropertyChanging("CHID");
                    _CHID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CHID");
                    OnCHIDChanged();
                }
            }
        }
        private global::System.Int32 _CHID;
        partial void OnCHIDChanging(global::System.Int32 value);
        partial void OnCHIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChallengeName
        {
            get
            {
                return _ChallengeName;
            }
            set
            {
                OnChallengeNameChanging(value);
                ReportPropertyChanging("ChallengeName");
                _ChallengeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChallengeName");
                OnChallengeNameChanged();
            }
        }
        private global::System.String _ChallengeName;
        partial void OnChallengeNameChanging(global::System.String value);
        partial void OnChallengeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BadgeID
        {
            get
            {
                return _BadgeID;
            }
            set
            {
                OnBadgeIDChanging(value);
                ReportPropertyChanging("BadgeID");
                _BadgeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BadgeID");
                OnBadgeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BadgeID;
        partial void OnBadgeIDChanging(Nullable<global::System.Int32> value);
        partial void OnBadgeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DogChallengeImage
        {
            get
            {
                return _DogChallengeImage;
            }
            set
            {
                OnDogChallengeImageChanging(value);
                ReportPropertyChanging("DogChallengeImage");
                _DogChallengeImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DogChallengeImage");
                OnDogChallengeImageChanged();
            }
        }
        private global::System.String _DogChallengeImage;
        partial void OnDogChallengeImageChanging(global::System.String value);
        partial void OnDogChallengeImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CatChallengeImage
        {
            get
            {
                return _CatChallengeImage;
            }
            set
            {
                OnCatChallengeImageChanging(value);
                ReportPropertyChanging("CatChallengeImage");
                _CatChallengeImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CatChallengeImage");
                OnCatChallengeImageChanged();
            }
        }
        private global::System.String _CatChallengeImage;
        partial void OnCatChallengeImageChanging(global::System.String value);
        partial void OnCatChallengeImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ChallengeCreatedDate
        {
            get
            {
                return _ChallengeCreatedDate;
            }
            set
            {
                OnChallengeCreatedDateChanging(value);
                ReportPropertyChanging("ChallengeCreatedDate");
                _ChallengeCreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChallengeCreatedDate");
                OnChallengeCreatedDateChanged();
            }
        }
        private global::System.DateTime _ChallengeCreatedDate;
        partial void OnChallengeCreatedDateChanging(global::System.DateTime value);
        partial void OnChallengeCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CatDescription
        {
            get
            {
                return _CatDescription;
            }
            set
            {
                OnCatDescriptionChanging(value);
                ReportPropertyChanging("CatDescription");
                _CatDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CatDescription");
                OnCatDescriptionChanged();
            }
        }
        private global::System.String _CatDescription;
        partial void OnCatDescriptionChanging(global::System.String value);
        partial void OnCatDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tagline
        {
            get
            {
                return _Tagline;
            }
            set
            {
                OnTaglineChanging(value);
                ReportPropertyChanging("Tagline");
                _Tagline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tagline");
                OnTaglineChanged();
            }
        }
        private global::System.String _Tagline;
        partial void OnTaglineChanging(global::System.String value);
        partial void OnTaglineChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="PetEarnBadge")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PetEarnBadge : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PetEarnBadge object.
        /// </summary>
        /// <param name="eBID">Initial value of the EBID property.</param>
        public static PetEarnBadge CreatePetEarnBadge(global::System.Int32 eBID)
        {
            PetEarnBadge petEarnBadge = new PetEarnBadge();
            petEarnBadge.EBID = eBID;
            return petEarnBadge;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EBID
        {
            get
            {
                return _EBID;
            }
            set
            {
                if (_EBID != value)
                {
                    OnEBIDChanging(value);
                    ReportPropertyChanging("EBID");
                    _EBID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EBID");
                    OnEBIDChanged();
                }
            }
        }
        private global::System.Int32 _EBID;
        partial void OnEBIDChanging(global::System.Int32 value);
        partial void OnEBIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PID
        {
            get
            {
                return _PID;
            }
            set
            {
                OnPIDChanging(value);
                ReportPropertyChanging("PID");
                _PID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PID");
                OnPIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PID;
        partial void OnPIDChanging(Nullable<global::System.Int32> value);
        partial void OnPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int32> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BID
        {
            get
            {
                return _BID;
            }
            set
            {
                OnBIDChanging(value);
                ReportPropertyChanging("BID");
                _BID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BID");
                OnBIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BID;
        partial void OnBIDChanging(Nullable<global::System.Int32> value);
        partial void OnBIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CID
        {
            get
            {
                return _CID;
            }
            set
            {
                OnCIDChanging(value);
                ReportPropertyChanging("CID");
                _CID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CID");
                OnCIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CID;
        partial void OnCIDChanging(Nullable<global::System.Int32> value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FBStatus
        {
            get
            {
                return _FBStatus;
            }
            set
            {
                OnFBStatusChanging(value);
                ReportPropertyChanging("FBStatus");
                _FBStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FBStatus");
                OnFBStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _FBStatus;
        partial void OnFBStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnFBStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TwitterStatus
        {
            get
            {
                return _TwitterStatus;
            }
            set
            {
                OnTwitterStatusChanging(value);
                ReportPropertyChanging("TwitterStatus");
                _TwitterStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TwitterStatus");
                OnTwitterStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _TwitterStatus;
        partial void OnTwitterStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnTwitterStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Pinterest
        {
            get
            {
                return _Pinterest;
            }
            set
            {
                OnPinterestChanging(value);
                ReportPropertyChanging("Pinterest");
                _Pinterest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pinterest");
                OnPinterestChanged();
            }
        }
        private Nullable<global::System.Boolean> _Pinterest;
        partial void OnPinterestChanging(Nullable<global::System.Boolean> value);
        partial void OnPinterestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ChCompleteDate
        {
            get
            {
                return _ChCompleteDate;
            }
            set
            {
                OnChCompleteDateChanging(value);
                ReportPropertyChanging("ChCompleteDate");
                _ChCompleteDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChCompleteDate");
                OnChCompleteDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ChCompleteDate;
        partial void OnChCompleteDateChanging(Nullable<global::System.DateTime> value);
        partial void OnChCompleteDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> BadgeEarn
        {
            get
            {
                return _BadgeEarn;
            }
            set
            {
                OnBadgeEarnChanging(value);
                ReportPropertyChanging("BadgeEarn");
                _BadgeEarn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BadgeEarn");
                OnBadgeEarnChanged();
            }
        }
        private Nullable<global::System.Boolean> _BadgeEarn;
        partial void OnBadgeEarnChanging(Nullable<global::System.Boolean> value);
        partial void OnBadgeEarnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                OnCatIDChanging(value);
                ReportPropertyChanging("CatID");
                _CatID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatID");
                OnCatIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CatID;
        partial void OnCatIDChanging(Nullable<global::System.Int32> value);
        partial void OnCatIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="PetProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PetProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PetProfile object.
        /// </summary>
        /// <param name="pID">Initial value of the PID property.</param>
        /// <param name="petName">Initial value of the PetName property.</param>
        /// <param name="petCategory">Initial value of the PetCategory property.</param>
        public static PetProfile CreatePetProfile(global::System.Int32 pID, global::System.String petName, global::System.String petCategory)
        {
            PetProfile petProfile = new PetProfile();
            petProfile.PID = pID;
            petProfile.PetName = petName;
            petProfile.PetCategory = petCategory;
            return petProfile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PID
        {
            get
            {
                return _PID;
            }
            set
            {
                if (_PID != value)
                {
                    OnPIDChanging(value);
                    ReportPropertyChanging("PID");
                    _PID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PID");
                    OnPIDChanged();
                }
            }
        }
        private global::System.Int32 _PID;
        partial void OnPIDChanging(global::System.Int32 value);
        partial void OnPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int32> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PetName
        {
            get
            {
                return _PetName;
            }
            set
            {
                OnPetNameChanging(value);
                ReportPropertyChanging("PetName");
                _PetName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PetName");
                OnPetNameChanged();
            }
        }
        private global::System.String _PetName;
        partial void OnPetNameChanging(global::System.String value);
        partial void OnPetNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PetBreed
        {
            get
            {
                return _PetBreed;
            }
            set
            {
                OnPetBreedChanging(value);
                ReportPropertyChanging("PetBreed");
                _PetBreed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PetBreed");
                OnPetBreedChanged();
            }
        }
        private global::System.String _PetBreed;
        partial void OnPetBreedChanging(global::System.String value);
        partial void OnPetBreedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PetCategory
        {
            get
            {
                return _PetCategory;
            }
            set
            {
                OnPetCategoryChanging(value);
                ReportPropertyChanging("PetCategory");
                _PetCategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PetCategory");
                OnPetCategoryChanged();
            }
        }
        private global::System.String _PetCategory;
        partial void OnPetCategoryChanging(global::System.String value);
        partial void OnPetCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PetImage
        {
            get
            {
                return _PetImage;
            }
            set
            {
                OnPetImageChanging(value);
                ReportPropertyChanging("PetImage");
                _PetImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PetImage");
                OnPetImageChanged();
            }
        }
        private global::System.String _PetImage;
        partial void OnPetImageChanging(global::System.String value);
        partial void OnPetImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String About
        {
            get
            {
                return _About;
            }
            set
            {
                OnAboutChanging(value);
                ReportPropertyChanging("About");
                _About = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("About");
                OnAboutChanged();
            }
        }
        private global::System.String _About;
        partial void OnAboutChanging(global::System.String value);
        partial void OnAboutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FavProduct
        {
            get
            {
                return _FavProduct;
            }
            set
            {
                OnFavProductChanging(value);
                ReportPropertyChanging("FavProduct");
                _FavProduct = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FavProduct");
                OnFavProductChanged();
            }
        }
        private global::System.String _FavProduct;
        partial void OnFavProductChanging(global::System.String value);
        partial void OnFavProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SecondBadge
        {
            get
            {
                return _SecondBadge;
            }
            set
            {
                OnSecondBadgeChanging(value);
                ReportPropertyChanging("SecondBadge");
                _SecondBadge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SecondBadge");
                OnSecondBadgeChanged();
            }
        }
        private Nullable<global::System.Int32> _SecondBadge;
        partial void OnSecondBadgeChanging(Nullable<global::System.Int32> value);
        partial void OnSecondBadgeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="Reward")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reward : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reward object.
        /// </summary>
        /// <param name="rID">Initial value of the RID property.</param>
        public static Reward CreateReward(global::System.Int32 rID)
        {
            Reward reward = new Reward();
            reward.RID = rID;
            return reward;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RID
        {
            get
            {
                return _RID;
            }
            set
            {
                if (_RID != value)
                {
                    OnRIDChanging(value);
                    ReportPropertyChanging("RID");
                    _RID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RID");
                    OnRIDChanged();
                }
            }
        }
        private global::System.Int32 _RID;
        partial void OnRIDChanging(global::System.Int32 value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UID;
        partial void OnUIDChanging(Nullable<global::System.Int32> value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WID
        {
            get
            {
                return _WID;
            }
            set
            {
                OnWIDChanging(value);
                ReportPropertyChanging("WID");
                _WID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WID");
                OnWIDChanged();
            }
        }
        private Nullable<global::System.Int32> _WID;
        partial void OnWIDChanging(Nullable<global::System.Int32> value);
        partial void OnWIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUnlocked
        {
            get
            {
                return _DateUnlocked;
            }
            set
            {
                OnDateUnlockedChanging(value);
                ReportPropertyChanging("DateUnlocked");
                _DateUnlocked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUnlocked");
                OnDateUnlockedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUnlocked;
        partial void OnDateUnlockedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUnlockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateClaimed
        {
            get
            {
                return _DateClaimed;
            }
            set
            {
                OnDateClaimedChanging(value);
                ReportPropertyChanging("DateClaimed");
                _DateClaimed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateClaimed");
                OnDateClaimedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateClaimed;
        partial void OnDateClaimedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateClaimedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="uID">Initial value of the UID property.</param>
        public static User CreateUser(global::System.Int32 uID)
        {
            User user = new User();
            user.UID = uID;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UID
        {
            get
            {
                return _UID;
            }
            set
            {
                if (_UID != value)
                {
                    OnUIDChanging(value);
                    ReportPropertyChanging("UID");
                    _UID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UID");
                    OnUIDChanged();
                }
            }
        }
        private global::System.Int32 _UID;
        partial void OnUIDChanging(global::System.Int32 value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fbid
        {
            get
            {
                return _fbid;
            }
            set
            {
                OnfbidChanging(value);
                ReportPropertyChanging("fbid");
                _fbid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fbid");
                OnfbidChanged();
            }
        }
        private global::System.String _fbid;
        partial void OnfbidChanging(global::System.String value);
        partial void OnfbidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String acesstoken
        {
            get
            {
                return _acesstoken;
            }
            set
            {
                OnacesstokenChanging(value);
                ReportPropertyChanging("acesstoken");
                _acesstoken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("acesstoken");
                OnacesstokenChanged();
            }
        }
        private global::System.String _acesstoken;
        partial void OnacesstokenChanging(global::System.String value);
        partial void OnacesstokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SharedToFacebookOn
        {
            get
            {
                return _SharedToFacebookOn;
            }
            set
            {
                OnSharedToFacebookOnChanging(value);
                ReportPropertyChanging("SharedToFacebookOn");
                _SharedToFacebookOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SharedToFacebookOn");
                OnSharedToFacebookOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _SharedToFacebookOn;
        partial void OnSharedToFacebookOnChanging(Nullable<global::System.DateTime> value);
        partial void OnSharedToFacebookOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SharedToTwitterOn
        {
            get
            {
                return _SharedToTwitterOn;
            }
            set
            {
                OnSharedToTwitterOnChanging(value);
                ReportPropertyChanging("SharedToTwitterOn");
                _SharedToTwitterOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SharedToTwitterOn");
                OnSharedToTwitterOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _SharedToTwitterOn;
        partial void OnSharedToTwitterOnChanging(Nullable<global::System.DateTime> value);
        partial void OnSharedToTwitterOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SharedToPinterestOn
        {
            get
            {
                return _SharedToPinterestOn;
            }
            set
            {
                OnSharedToPinterestOnChanging(value);
                ReportPropertyChanging("SharedToPinterestOn");
                _SharedToPinterestOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SharedToPinterestOn");
                OnSharedToPinterestOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _SharedToPinterestOn;
        partial void OnSharedToPinterestOnChanging(Nullable<global::System.DateTime> value);
        partial void OnSharedToPinterestOnChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PHCModel", Name="Wallpaper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Wallpaper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Wallpaper object.
        /// </summary>
        /// <param name="wID">Initial value of the WID property.</param>
        public static Wallpaper CreateWallpaper(global::System.Int32 wID)
        {
            Wallpaper wallpaper = new Wallpaper();
            wallpaper.WID = wID;
            return wallpaper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WID
        {
            get
            {
                return _WID;
            }
            set
            {
                if (_WID != value)
                {
                    OnWIDChanging(value);
                    ReportPropertyChanging("WID");
                    _WID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WID");
                    OnWIDChanged();
                }
            }
        }
        private global::System.Int32 _WID;
        partial void OnWIDChanging(global::System.Int32 value);
        partial void OnWIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WallImage
        {
            get
            {
                return _WallImage;
            }
            set
            {
                OnWallImageChanging(value);
                ReportPropertyChanging("WallImage");
                _WallImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WallImage");
                OnWallImageChanged();
            }
        }
        private global::System.String _WallImage;
        partial void OnWallImageChanging(global::System.String value);
        partial void OnWallImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BadgesNeeded
        {
            get
            {
                return _BadgesNeeded;
            }
            set
            {
                OnBadgesNeededChanging(value);
                ReportPropertyChanging("BadgesNeeded");
                _BadgesNeeded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BadgesNeeded");
                OnBadgesNeededChanged();
            }
        }
        private Nullable<global::System.Int32> _BadgesNeeded;
        partial void OnBadgesNeededChanging(Nullable<global::System.Int32> value);
        partial void OnBadgesNeededChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUnlocks
        {
            get
            {
                return _DateUnlocks;
            }
            set
            {
                OnDateUnlocksChanging(value);
                ReportPropertyChanging("DateUnlocks");
                _DateUnlocks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUnlocks");
                OnDateUnlocksChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUnlocks;
        partial void OnDateUnlocksChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUnlocksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ICGPin
        {
            get
            {
                return _ICGPin;
            }
            set
            {
                OnICGPinChanging(value);
                ReportPropertyChanging("ICGPin");
                _ICGPin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ICGPin");
                OnICGPinChanged();
            }
        }
        private global::System.String _ICGPin;
        partial void OnICGPinChanging(global::System.String value);
        partial void OnICGPinChanged();

        #endregion

    
    }

    #endregion

    
}
